import { useState } from "react";
import {
  AlertTriangle,
  ArrowRight,
  Bot,
  CheckCircle2,
  Clock,
  HelpCircle,
  Layers,
  ShieldAlert,
  ShieldCheck,
  Sparkles,
  Wand2,
  X,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import type { ExtendedTemplate } from "@/lib/kneawork/template-types";

interface AiWorkflowGeneratorDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onReviewDraft: (draftTemplate: ExtendedTemplate) => void;
}

export function AiWorkflowGeneratorDialog({
  open,
  onOpenChange,
  onReviewDraft,
}: AiWorkflowGeneratorDialogProps) {
  const [prompt, setPrompt] = useState(
    "Create a purchase request for purchases above USD 100. Finance checks the quotation first, then the department manager approves, and the director confirms purchases above USD 10,000.",
  );
  const [isGenerating, setIsGenerating] = useState(false);
  const [hasGenerated, setHasGenerated] = useState(false);

  // Simulated AI parse result matching the spec
  const understoodPoints = [
    "Workflow Type: Purchase Request (procurement & vendor purchases)",
    "Evidence Policy: Supplier quotation required for amounts above $100 USD",
    "Approval Step 1: Finance Review (checks quotation and budget)",
    "Approval Step 2: Manager Approval (validates team necessity)",
    "Approval Step 3: Director Confirmation (triggers for amounts ≥ $10,000 USD)",
    "Spend Ceiling: Requires executive sign-off for large capital expenses",
  ];

  const clarificationPoints = [
    "Who receives requests when the department has no assigned manager?",
    "How long should each sequential review step take (defaulting to 1–2 days)?",
    "Should purchases under $100 skip Finance and go directly to Manager?",
  ];

  const sampleDraftTemplate: ExtendedTemplate = {
    id: `tpl_ai_${Date.now()}`,
    type: "purchase",
    label: "Purchase Request (AI Draft)",
    description: "Standard procurement process generated by AI draft assistant for goods, services, and vendor orders.",
    category: "purchase",
    departmentScope: "All Departments",
    whoCanSubmit: "All employees",
    ownerId: "u_admin",
    ownerName: "Dara · Operations Admin",
    typicalCompletionTime: "2-3 business days",
    completionOutcome: "Purchase order is approved and forwarded to accounting for disbursement.",
    version: "1.0",
    versionStatus: "Draft",
    updatedDate: "Just now",
    usageCount: 0,
    lastUsed: "Never",
    fields: [
      {
        id: "f_title",
        label: "Item or Service Name",
        type: "text",
        helpText: "e.g. Dell UltraSharp 27-inch Monitor",
        required: true,
        section: "required",
      },
      {
        id: "f_vendor",
        label: "Supplier / Vendor Name",
        type: "text",
        helpText: "e.g. Anana Computer Co., Ltd.",
        required: true,
        section: "required",
      },
      {
        id: "f_amount",
        label: "Total Amount (USD)",
        type: "amount",
        helpText: "Total quoted price including taxes",
        required: true,
        section: "required",
      },
      {
        id: "f_justification",
        label: "Business Justification",
        type: "textarea",
        helpText: "Why is this purchase necessary for company operations?",
        required: true,
        section: "required",
      },
      {
        id: "f_quotation",
        label: "Supplier Quotation PDF",
        type: "file",
        helpText: "Mandatory for amounts over $100 USD",
        required: true,
        section: "supporting",
      },
    ],
    routeSteps: [
      {
        id: "step_finance",
        name: "Finance Review",
        roleId: "role_finance",
        roleName: "Finance Reviewer",
        assigneeId: "u_finance",
        assigneeName: "Vanna",
        responsibility: "Verify supplier quotation against market rates and check budget allocation.",
        decisionType: "single",
        dueDays: 1,
        onOverdue: "remind",
      },
      {
        id: "step_manager",
        name: "Manager Approval",
        roleId: "role_manager",
        roleName: "Manager Approver",
        assigneeId: "u_manager",
        assigneeName: "Sokha",
        responsibility: "Confirm operational necessity and authorize department spend.",
        decisionType: "single",
        dueDays: 1,
        onOverdue: "remind",
      },
      {
        id: "step_director",
        name: "Director Confirmation",
        roleId: "role_director",
        roleName: "Managing Director",
        assigneeId: "u_director",
        assigneeName: "Mr. Lim",
        responsibility: "Final executive confirmation for major purchases exceeding $10,000 USD.",
        decisionType: "single",
        dueDays: 2,
        onOverdue: "escalate",
      },
    ],
    rules: {
      departmentScope: "All Departments",
      minAmount: 1,
      maxAmount: 25000,
      requireQuotation: true,
      quotationThreshold: 100,
      requireReceipt: false,
      requireManagerNote: true,
      requireLegalAssessment: false,
      allowedFileTypes: [".pdf", ".jpg", ".png"],
      maxFileSizeMb: 10,
      conditionalDirectorAbove: 10000,
      onMissingEvidence: "prevent",
    },
  };

  const handleGenerate = () => {
    setIsGenerating(true);
    setTimeout(() => {
      setIsGenerating(false);
      setHasGenerated(true);
    }, 600);
  };

  const handleReviewDraft = () => {
    onOpenChange(false);
    onReviewDraft(sampleDraftTemplate);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-2xl max-h-[85vh] overflow-y-auto">
        <DialogHeader className="border-b border-border pb-3">
          <div className="flex items-center gap-2">
            <span className="flex size-7 items-center justify-center rounded-full bg-primary/10 text-primary">
              <Sparkles className="size-4" />
            </span>
            <div>
              <DialogTitle className="text-base sm:text-lg font-bold text-foreground">
                AI Workflow Draft Generator
              </DialogTitle>
              <DialogDescription className="text-xs text-muted-foreground">
                Describe company policies in plain English or Khmer · AI generates a governed draft for human review
              </DialogDescription>
            </div>
          </div>
        </DialogHeader>

        {/* AI Guardrails Callout */}
        <div className="rounded-lg border border-primary/20 bg-primary/5 p-3 text-xs text-foreground flex items-start gap-2.5">
          <ShieldCheck className="size-4 text-primary shrink-0 mt-0.5" />
          <div className="leading-relaxed">
            <strong>Governed AI Architecture:</strong> AI generates structured drafts only. It can{" "}
            <strong>never</strong> automatically publish, modify in-flight requests, or approve
            requests. A human administrator must inspect and test all rules before activating.
          </div>
        </div>

        {/* Prompt Input Area */}
        <div className="space-y-3">
          <div className="space-y-1.5">
            <Label htmlFor="ai-prompt" className="text-xs font-semibold text-foreground">
              Describe your workflow policy or approval process:
            </Label>
            <Textarea
              id="ai-prompt"
              rows={3}
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              placeholder="e.g. When an employee requests equipment above $200, Finance reviews first, then department manager approves..."
              className="text-xs sm:text-sm bg-card resize-none"
            />
          </div>

          {/* Quick presets */}
          <div className="flex items-center gap-1.5 flex-wrap">
            <span className="text-[11px] text-muted-foreground mr-1">Presets:</span>
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={() => {
                setPrompt(
                  "Create a purchase request for purchases above USD 100. Finance checks quotation first, then manager approves, and director confirms purchases above USD 10,000.",
                );
                setHasGenerated(false);
              }}
              className="text-[11px] h-6 px-2 text-muted-foreground hover:text-foreground"
            >
              Purchase ($100+ quotation)
            </Button>
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={() => {
                setPrompt(
                  "Create an employee travel expense claim requiring tax receipts. Department lead signs off, then finance verifies payment within 2 days.",
                );
                setHasGenerated(false);
              }}
              className="text-[11px] h-6 px-2 text-muted-foreground hover:text-foreground"
            >
              Expense (Receipt required)
            </Button>
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={() => {
                setPrompt(
                  "Create a vendor commercial contract approval. Legal reviews draft first, Finance verifies commercial value, Managing Director provides final signature.",
                );
                setHasGenerated(false);
              }}
              className="text-[11px] h-6 px-2 text-muted-foreground hover:text-foreground"
            >
              Contract (3-stage legal)
            </Button>
          </div>

          <Button
            type="button"
            onClick={handleGenerate}
            disabled={isGenerating || !prompt.trim()}
            className="w-full bg-primary text-primary-foreground hover:bg-primary-hover font-semibold text-xs h-9 gap-1.5 shadow-2xs"
          >
            <Wand2 className="size-3.5" />
            {isGenerating ? "Analyzing policies & generating draft..." : "Generate structured draft"}
          </Button>
        </div>

        {/* Results Preview Panel */}
        {hasGenerated && (
          <div className="space-y-4 pt-3 border-t border-border">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <CheckCircle2 className="size-4 text-success" />
                <h4 className="text-sm font-bold text-foreground">Draft Workflow Proposal Ready</h4>
              </div>
              <span className="rounded bg-attention-soft border border-attention-border px-2 py-0.5 text-xs font-semibold text-attention">
                v1.0 Draft (Unpublished)
              </span>
            </div>

            {/* 1. What AI Understood */}
            <div className="rounded-lg border border-success-border/60 bg-success-soft/20 p-3.5 space-y-2 text-xs">
              <span className="font-bold text-success flex items-center gap-1.5">
                <CheckCircle2 className="size-3.5" />
                What the system understood:
              </span>
              <ul className="space-y-1 text-foreground">
                {understoodPoints.map((point, i) => (
                  <li key={i} className="flex items-start gap-2">
                    <span className="text-success font-bold shrink-0">•</span>
                    <span>{point}</span>
                  </li>
                ))}
              </ul>
            </div>

            {/* 2. Missing Information / Clarifications Needed */}
            <div className="rounded-lg border border-warning-border/60 bg-warning-soft/20 p-3.5 space-y-2 text-xs">
              <span className="font-bold text-warning flex items-center gap-1.5">
                <AlertTriangle className="size-3.5" />
                Assumptions & clarifications needed:
              </span>
              <ul className="space-y-1 text-foreground">
                {clarificationPoints.map((point, i) => (
                  <li key={i} className="flex items-start gap-2">
                    <span className="text-warning font-bold shrink-0">!</span>
                    <span>{point}</span>
                  </li>
                ))}
              </ul>
            </div>

            {/* 3. Draft Blueprint Summary */}
            <div className="rounded-lg border border-border bg-card p-3.5 space-y-2.5 text-xs">
              <div className="flex items-center justify-between border-b border-border pb-1.5">
                <span className="font-semibold text-foreground">Generated Step Route</span>
                <span className="text-muted-foreground">3 sequential checkpoints</span>
              </div>
              <div className="flex items-center gap-1.5 flex-wrap">
                <span className="rounded bg-muted px-2 py-0.5 border border-border font-medium text-foreground">
                  Requester
                </span>
                <span className="text-muted-foreground">→</span>
                <span className="rounded bg-muted px-2 py-0.5 border border-border font-medium text-foreground">
                  1. Finance Review (~1d)
                </span>
                <span className="text-muted-foreground">→</span>
                <span className="rounded bg-muted px-2 py-0.5 border border-border font-medium text-foreground">
                  2. Manager Approval (~1d)
                </span>
                <span className="text-muted-foreground">→</span>
                <span className="rounded bg-muted px-2 py-0.5 border border-border font-medium text-foreground">
                  3. Director Confirmation (~2d, ≥$10k)
                </span>
              </div>
            </div>

            {/* Human Hand-Off Actions */}
            <div className="flex items-center justify-between pt-2">
              <Button
                type="button"
                variant="outline"
                size="sm"
                onClick={() => setHasGenerated(false)}
                className="text-xs"
              >
                Refine prompt
              </Button>

              <Button
                type="button"
                size="sm"
                onClick={handleReviewDraft}
                className="bg-primary text-primary-foreground hover:bg-primary-hover font-semibold text-xs gap-1.5 shadow-2xs"
              >
                Review draft in Template Builder
                <ArrowRight className="size-3.5" />
              </Button>
            </div>
          </div>
        )}

        <DialogFooter className="border-t border-border pt-3">
          <Button size="sm" variant="outline" onClick={() => onOpenChange(false)} className="text-xs">
            Close
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
